name: run jest tests

on:
  push
# branches: [ master ]

jobs:
  test_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: create mongodb docker container for testing
        uses: DigiPie/mongo-action@v2.0.1
      - run: yarn install
      - run: yarn run test
